### ISSUE TITLE
🎃 October Roadmap

### ISSUE THREAD

**Issue by lzrscg** [modularcloud/explorer#200]
# Known Bugs
- [x] #206
- [x] #197
- [x] #209
- [x] #222  
- [x] #196 
- [x] #193 
- [x] #204 
- [x] #211
- [x] #210
- [ ] #208 
- [x] #226
- [ ] Use correct logos and chain names (backend)

# Outstanding General Features
- [x] #194 
- [x] #203

# Outstanding Celestia Features
- [x] Namespace page (in progress)
- [x] View blobs by block
- [x] View transactions by block 
- [x] View blobs by transaction
- [x] View messages by transaction (in progress)
- [ ] Address balances and transaction history (backend in progress)
- [x] Validator information (backend in progress)

# Stretch Goals
- [ ] #205
- [x] #212
 
# Upcoming
- #214 
- #215
